export const dataCards = [
  {
    title: "Total Revenue",
    text: "(Last 30 Days)",
    total: 0,
    label: "warning",
  },
  { title: "Total Order", text: "(Last 30 Days)", total: 0 },
  { title: "Todays Revenue", text: "qqq", total: 10 },
  { title: "Total Shops", text: "", total: 15 },
];

export const columns = [
  {
    name: "name",
    required: true,
    label: "Tracking Number",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "calories",
    align: "left",
    label: "Total",
    field: "calories",
    sortable: true,
  },
  // { name: "fat", label: "Fat (g)", field: "fat", sortable: true },
  // { name: "carbs", label: "Carbs (g)", field: "carbs" },
  { name: "protein", align: "left", label: "Amount", field: "protein" },
  { name: "sodium", align: "left", label: "Weight", field: "sodium" },
  {
    name: "status",
    label: "Status",
    align: "left",
    field: "status",
    // sortable: true,
    // sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
];

export const rows = [
  {
    name: "Frozen Yogurt",
    calories: 159,
    // fat: 6.0,
    // carbs: 24,
    protein: 4.0,
    sodium: 87,
    status: "Order Received",
  },
  {
    name: "Ice cream sandwich",
    calories: 237,
    // fat: 9.0,
    // carbs: 37,
    protein: 4.3,
    sodium: 129,
    status: "Order Received",
  },
  {
    name: "Eclair",
    calories: 262,
    // fat: 16.0,
    // carbs: 23,
    protein: 6.0,
    sodium: 337,
    status: "Order Received",
  },
  {
    name: "Cupcake",
    calories: 305,
    // fat: 3.7,
    // carbs: 67,
    protein: 4.3,
    sodium: 413,
    status: "Order Received",
  },
  {
    name: "Gingerbread",
    calories: 356,
    // fat: 16.0,
    // carbs: 49,
    protein: 3.9,
    sodium: 327,
    status: "Order Received",
  },
  {
    name: "Jelly bean",
    calories: 375,
    // fat: 0.0,
    // carbs: 94,
    protein: 0.0,
    sodium: 50,
    status: "Order Received",
  },
  {
    name: "Lollipop",
    calories: 392,
    // fat: 0.2,
    // carbs: 98,
    protein: 0,
    sodium: 38,
    status: "Order Received",
  },
  {
    name: "Honeycomb",
    calories: 408,
    // fat: 3.2,
    // carbs: 87,
    protein: 6.5,
    sodium: 562,
    status: "Order Received",
  },
  {
    name: "Donut",
    calories: 452,
    // fat: 25.0,
    // carbs: 51,
    protein: 4.9,
    sodium: 326,
    status: "Order Received",
  },
  {
    name: "KitKat",
    calories: 518,
    // fat: 26.0,
    // carbs: 65,
    protein: 7,
    sodium: 54,
    status: "Order Received",
  },
];
