export const columns = [
  {
    name: "avatar",
    // required: true,
    label: "Avatar",
    align: "left",
    // field: (row: { name: string }) => row.name,
    // format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "name",
    required: true,
    align: "center",
    label: "Name",
    field: "name",
    sortable: true,
  },
  {
    name: "email",
    required: true,
    align: "center",
    label: "Email",
    field: "email",
    sortable: true,
  },
  // { name: "fat", label: "Fat (g)", field: "fat", sortable: true },
  // { name: "carbs", label: "Carbs (g)", field: "carbs" },
  // { name: "protein", label: "Protein (g)", field: "protein" },
  // { name: "sodium", label: "Sodium (mg)", field: "sodium" },
  // {
  //   name: "calcium",
  //   label: "Calcium (%)",
  //   field: "calcium",
  //   sortable: true,
  //   sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  // },
  // {
  //   name: "iron",
  //   label: "Iron (%)",
  //   field: "iron",
  //   sortable: true,
  //   sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  // },
  { name: "actions", label: "Actions" },
];

export const rows = [
  {
    avatar: "https://cdn.quasar.dev/app-icons/icon-128x128.png",
    name: "user1",
    email: "user1@mail.com",
    // category: "breakfast",
    // calories: 159,
    // fat: 6.0,
    // carbs: 24,
    // protein: 4.0,
    // sodium: 87,
    // calcium: "14%",
    // iron: "1%",
    // url: "https://cdn.quasar.dev/app-icons/icon-128x128.png",
  },
  {
    avatar: "https://cdn.quasar.dev/app-icons/icon-128x128.png",
    name: "user2",
    email: "user2@mail.com",
    // category: "breakfast",
    // calories: 237,
    // fat: 9.0,
    // carbs: 37,
    // protein: 4.3,
    // sodium: 129,
    // calcium: "8%",
    // iron: "1%",
    // url: "https://cdn.quasar.dev/app-icons/icon-128x128.png",
  },
  {
    avatar: "",
    name: "user3",
    email: "user3@mail.com",
    //   category: "lunch",
    //   calories: 262,
    //   fat: 16.0,
    //   carbs: 23,
    //   protein: 6.0,
    //   sodium: 337,
    //   calcium: "6%",
    //   iron: "7%",
  },
  {
    // avatar: "Cupcake",
    name: "user4",
    email: "user4@mail.com",
    // category: "lunch",
    // calories: 305,
    // fat: 3.7,
    // carbs: 67,
    // protein: 4.3,
    // sodium: 413,
    // calcium: "3%",
    // iron: "8%",
  },
  {
    name: "user5",
    email: "user5@mail.com",
    // name: "Gingerbread",
    // category: "dinner",
    // calories: 356,
    // fat: 16.0,
    // carbs: 49,
    // protein: 3.9,
    // sodium: 327,
    // calcium: "7%",
    // iron: "16%",
  },
  {
    name: "user6",
    email: "user6@mail.com",
    // name: "Jelly bean",
    // category: "dinner",
    // calories: 375,
    // fat: 0.0,
    // carbs: 94,
    // protein: 0.0,
    // sodium: 50,
    // calcium: "0%",
    // iron: "0%",
  },
  {
    name: "user7",
    email: "user7@mail.com",
    // name: "Lollipop",
    // category: "dinner",
    // calories: 392,
    // fat: 0.2,
    // carbs: 98,
    // protein: 0,
    // sodium: 38,
    // calcium: "0%",
    // iron: "2%",
  },
  {
    name: "user8",
    email: "user8@mail.com",
    // name: "Honeycomb",
    // category: "breakfast",
    // calories: 408,
    // fat: 3.2,
    // carbs: 87,
    // protein: 6.5,
    // sodium: 562,
    // calcium: "0%",
    // iron: "45%",
  },
  {
    name: "user9",
    email: "user9@mail.com",
    // name: "Donut",
    // category: "lunch",
    // calories: 452,
    // fat: 25.0,
    // carbs: 51,
    // protein: 4.9,
    // sodium: 326,
    // calcium: "2%",
    // iron: "22%",
  },
  {
    name: "user10",
    email: "user10@mail.com",
    // name: "KitKat",
    // category: "breakfast",
    // calories: 518,
    // fat: 26.0,
    // carbs: 65,
    // protein: 7,
    // sodium: 54,
    // calcium: "12%",
    // iron: "6%",
  },
];
